### ISSUE TITLE
Mime type of yanked content?

### ISSUE THREAD

**Issue by seqizz** [ojroques/vim-oscyank#13]
Hi :wave: 

First of all, thanks for this plugin. I have a weird issue which causes yanked content to show up on clipboard history but not able to paste it (xclip reports its targets are empty).

Related ticket on greenclip side: https://github.com/erebe/greenclip/issues/116

Am I doing something wrong, or is there a tunable for the plugin? :eyes:

**Comment by ojroques** [comment]
Hello!

The plugin is pretty simple: when you select some text and call `:OSCYank`, the only thing the plugin does is to encode the text in base64 and emit the result with the OSC52 sequence code in front of it (it basically does `echo <OSC52;your-text-in-base64>`

Then it's your terminal that does the processing: when it sees any string with OSC52 in front of it, it decodes the string that follows and put it in your system clipboard. That's why the plugin work through SSH. So from the point of view of the plugin, there's no MIME type to handle or any other stuff.

So I think it's an issue with your terminal. What terminal are you using?

**Comment by seqizz** [comment]
Thanks for the explanation, It really sounds simple, I'll close this one. I'm using wezterm and currently walking between projects to find out the missing link :)
