### ISSUE TITLE
Getting it to work in urxvt

### ISSUE THREAD

**Issue by mgarort** [ojroques/vim-oscyank#4]
Hi,

I have arrived here following [the Reddit post where this plugin was announced](https://www.reddit.com/r/vim/comments/k1ydpn/a_guide_on_how_to_copy_text_from_anywhere/). I was very excited to see that the terminal I use, urxvt, was on the list of terminals that support OCS52. However, I haven't been able to make it work. Furthermore, I've seen that urxvt is not on the list of supporting terminals in the GitHub readme, even though it was included in the Reddit post.

Is it possible to use this plugin in urxvt, and do you have any pointers to make it work?

Thanks in advance!

**Comment by ojroques** [comment]
Hello!

I initially thought urxvt had support for OSC52 based on a random post saying so ([here](https://mail.gnome.org/archives/gnome-utils-list/2017-January/msg00000.html)) and given that rxvt seems to have OSC52 ([source](https://news.ycombinator.com/item?id=13551451)). But someone on reddit told me it was not the case. That's why I updated the README here. Sorry for getting your hopes up, I'll update the post on reddit.

I found this [small script](https://github.com/parantapa/dotfiles/blob/master/urxvt-perl/52-osc) claiming to add support maybe it'll be useful to you.

**Comment by mgarort** [comment]
Wow, thanks a lot! That script does indeed add support for OSC52, so I can finally use your plugin (and it's great, thanks!).

For future referece, to add OSC52 functionality to urxvt with this script you need to:
- Copy the script to `~/.urxvt/ext/52-osc`.
- Make urxvt source it by adding the following line to your `~/.Xdefaults` configuration file: `URxvt.perl-ext-common: 52-osc`.

Maybe this could be mentioned in the documentation? I know other urxvt users will find it useful too.

**Comment by ojroques** [comment]
Glad to hear that it worked! In case the repo is lost I've created a gist with the script [here](https://gist.github.com/ojroques/30e9ada6edd9226f9cc1d6776ece31cc). I'll update the readme and the reddit post with your instructions. Thanks.

**Comment by nuclight** [comment]
I'll paste script here in case links will be unavailable (first one already, second is unintuitively rendered by GitHub):
```perl
use MIME::Base64;
use Encode;

sub on_osc_seq {
    my ($term, $op, $args) = @_;
    return () unless $op eq 52;

    my ($clip, $data) = split ';', $args, 2;
    if ($data eq '?') {
        my $data_free = $term->selection();
        Encode::_utf8_off($data_free); # XXX
        $term->tt_write("\e]52;$clip;".encode_base64($data_free, '')."\a");
    }
    else {
        my $data_decoded = decode_base64($data);
        Encode::_utf8_on($data_decoded); # XXX
        $term->selection($data_decoded, $clip =~ /c/);
        $term->selection_grab(urxvt::CurrentTime, $clip =~ /c/);
    }

    ()
}
```
